let user=null,currentEntity=null,currentRows=[];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const labels={Students:"Data Siswa",Teachers:"Data Guru",Classes:"Kelas",Subjects:"Mata Pelajaran",Grades:"Nilai",Attendance:"Presensi",Courses:"Kelas LMS",Materials:"Materi",Assignments:"Tugas",Submissions:"Pengumpulan",Announcements:"Pengumuman"};
const schemas={Students:["ID","NISN","Nama","Kelas","JK","Email","Status"],Teachers:["ID","NIP","Nama","Mapel","Email","Status"],Classes:["ID","Kode","Nama Kelas","Wali Kelas","Tahun Ajaran"],Subjects:["ID","Kode","Nama","Guru","KKM"],Grades:["ID","Siswa","Mapel","Tugas","UTS","UAS","Nilai Akhir","Semester","Tahun Ajaran"],Attendance:["ID","Tanggal","Siswa","Kelas","Mapel","Status","Keterangan"],Courses:["ID","Kode","Nama Kursus","Guru","Deskripsi","Status"],Materials:["ID","Kursus","Judul","Deskripsi","URL","Tanggal","Status"],Assignments:["ID","Kursus","Judul","Deskripsi","URL","Batas Waktu","Status"],Submissions:["ID","AssignmentID","SiswaID","JawabanURL","TanggalKumpul","Status"],Announcements:["ID","Judul","Isi","Tanggal","Status"]};
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function notify(m,ok=true){const t=$("#toast");t.textContent=m;t.className="toast-msg show "+(ok?"ok":"error");setTimeout(()=>t.classList.remove("show"),3000)}
function payload(x={}){return{...x,token:user?.token}}
function clearSession(){user=null;localStorage.removeItem("siakad_user");location.reload()}
$("#form").onsubmit=async e=>{e.preventDefault();const b=$("#loginBtn");b.disabled=true;b.textContent="Memeriksa...";const r=await API.call("login",{username:$("#username").value.trim(),password:$("#password").value});b.disabled=false;b.textContent="Masuk";if(!r.success)return notify(r.message||"Login gagal",false);user={...r.user,token:r.token};localStorage.setItem("siakad_user",JSON.stringify(user));start()};
async function start(){if(!user)return;$("#login").classList.add("d-none");$("#app").classList.remove("d-none");if($("#who"))$("#who").textContent=user.nama;if($("#roleBadge"))$("#roleBadge").textContent=user.role;if($("#topUser"))$("#topUser").textContent=user.nama+" • "+user.role;if($("#topDate"))$("#topDate").textContent=new Intl.DateTimeFormat("id-ID",{dateStyle:"full"}).format(new Date());applyMenu();const r=await API.call("dashboard",payload());if(!r.success){if(/sesi|kedaluwarsa|valid/i.test(r.message||""))clearSession();else notify(r.message,false);return}renderDashboard(r.stats||{})}
function applyMenu(){$$("aside button[data-page]").forEach(b=>{const p=b.dataset.page;let show=p==="dashboard";if(user.role==="Admin")show=true;else if(user.role==="Guru")show=["Students","Teachers","Classes","Subjects","Grades","Attendance","Courses","Materials","Assignments","Submissions","Announcements"].includes(p);else if(user.role==="Siswa")show=["Courses","Materials","Assignments","Submissions","Grades","Attendance","Announcements"].includes(p);b.style.display=show?"block":"none"})}
$("#logout").onclick=async()=>{await API.call("logout",payload());clearSession()};$("#toggle").onclick=()=>$("#side").classList.toggle("hide");$$("aside button[data-page]").forEach(b=>b.onclick=()=>load(b.dataset.page));
function renderDashboard(s){const items=Object.entries(s);const name=esc(user.nama);const role=esc(user.role);$("#content").innerHTML=`<div class="dashboard-head mb-4"><div><div class="eyebrow">RINGKASAN SISTEM</div><h2 class="fw-bold mb-1">Dashboard</h2><p class="text-secondary mb-0">Selamat datang kembali, ${name} 👋</p></div><span class="role-pill">SIAKAD • ${role}</span></div><div class="row g-3">${items.map(([k,v])=>`<div class="col-6 col-xl-3"><div class="stat-card"><div class="stat-icon">◈</div><small>${esc(k)}</small><h2>${esc(v)}</h2><span class="stat-caption">Data tersimpan</span></div></div>`).join("")}</div><div class="row g-3 mt-1"><div class="col-lg-8"><div class="panel-card"><div class="panel-title"><span>Ringkasan Akademik</span><span class="live-dot">● LIVE</span></div><canvas id="chart"></canvas></div></div><div class="col-lg-4"><div class="panel-card h-100"><div class="panel-title">Akses Cepat</div><div class="quick-grid"><button onclick="load('Students')">👨‍🎓<span>Siswa</span></button><button onclick="load('Grades')">📝<span>Nilai</span></button><button onclick="load('Attendance')">📅<span>Presensi</span></button><button onclick="load('Announcements')">📢<span>Info</span></button></div></div></div></div>`;new Chart($("#chart"),{type:"bar",data:{labels:Object.keys(s),datasets:[{label:"Jumlah",data:Object.values(s),borderRadius:8}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}})}
async function load(page){currentEntity=page;$$("aside button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));const r=await API.call("list",payload({entity:page}));if(!r.success){if(/sesi|kedaluwarsa|valid/i.test(r.message||""))clearSession();else notify(r.message,false);return}currentRows=r.data||[];renderTable(page,currentRows)}
function renderTable(entity,rows){const cols=schemas[entity]||Object.keys(rows[0]||{});$("#content").innerHTML='<div class="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-3"><div><h2 class="fw-bold">'+labels[entity]+'</h2><span class="text-secondary">'+rows.length+' data</span></div><div class="d-flex gap-2"><input id="search" class="form-control searchbox" placeholder="Cari data..."><button class="btn btn-primary" id="add">+ Tambah</button></div></div><div class="card shadow-sm p-3"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr>'+cols.map(c=>'<th>'+esc(c)+'</th>').join("")+'<th>Aksi</th></tr></thead><tbody>'+rows.map((x,i)=>'<tr>'+cols.map(c=>'<td>'+esc(x[c])+'</td>').join("")+'<td><button class="btn btn-sm btn-outline-primary edit" data-i="'+i+'">Edit</button> <button class="btn btn-sm btn-outline-danger del" data-id="'+esc(x.ID)+'">Hapus</button></td></tr>').join("")+'</tbody></table></div></div>';$("#search").oninput=e=>renderTable(entity,rows.filter(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(e.target.value.toLowerCase()))));$("#add").onclick=()=>openForm(entity);$$(".edit").forEach(b=>b.onclick=()=>openForm(entity,rows[+b.dataset.i]));$$(".del").forEach(b=>b.onclick=async()=>{if(!confirm("Hapus data ini?"))return;const r=await API.call("delete",payload({entity,id:b.dataset.id}));notify(r.message,r.success);if(r.success)load(entity)})}
function openForm(entity,row={}){const cols=schemas[entity]||Object.keys(row);$("#modalTitle").textContent=(row.ID?"Edit ":"Tambah ")+labels[entity];$("#fields").innerHTML=cols.filter(k=>k!=="ID").map(k=>{const type=/tanggal|batas waktu/i.test(k)?"date":/deskripsi|isi|keterangan/i.test(k)?"textarea":"text";return '<div class="mb-3"><label class="form-label">'+esc(k)+'</label>'+(type==="textarea"?'<textarea class="form-control" name="'+esc(k)+'">'+esc(row[k]??"")+'</textarea>':'<input class="form-control" type="'+type+'" name="'+esc(k)+'" value="'+esc(row[k]??"")+'">')+'</div>'}).join("")+(row.ID?'<input type="hidden" name="ID" value="'+esc(row.ID)+'">':"");const modal=bootstrap.Modal.getOrCreateInstance($("#dataModal"));$("#dataForm").onsubmit=async e=>{e.preventDefault();const d={};new FormData(e.target).forEach((v,k)=>d[k]=v);const r=await API.call(row.ID?"update":"create",payload({entity,data:d,id:row.ID}));if(!r.success)return notify(r.message,false);modal.hide();notify(r.message);load(entity)};modal.show()}
try{user=JSON.parse(localStorage.getItem("siakad_user")||"null")}catch(e){clearSession()}if(user)start();