const SPREADSHEET_ID="1gEZu_8HjIJLMJ9PE3tV1a7GZfhk5N5qbhyxn9DxU-EA";
const SHEETS={Users:["ID","Username","Password","Nama","Role","Email","Status","CreatedAt"],Students:["ID","NISN","Nama","Kelas","JK","Email","Status"],Teachers:["ID","NIP","Nama","Mapel","Email","Status"],Classes:["ID","Kode","Nama Kelas","Wali Kelas","Tahun Ajaran"],Subjects:["ID","Kode","Nama","Guru","KKM"],Courses:["ID","Kode","Nama Kursus","Guru","Deskripsi","Status"],Materials:["ID","Kursus","Judul","Deskripsi","URL","Tanggal","Status"],Assignments:["ID","Kursus","Judul","Deskripsi","URL","Batas Waktu","Status"],Submissions:["ID","AssignmentID","SiswaID","JawabanURL","TanggalKumpul","Status"],Grades:["ID","Siswa","Mapel","Tugas","UTS","UAS","Nilai Akhir","Semester","Tahun Ajaran"],Attendance:["ID","Tanggal","Siswa","Kelas","Mapel","Status","Keterangan"],Announcements:["ID","Judul","Isi","Tanggal","Status"],Settings:["Key","Value"],ActivityLog:["Timestamp","Username","Action","Entity","RecordID"]};
const ROLES={Admin:["*"],Guru:["Students","Classes","Subjects","Courses","Materials","Assignments","Submissions","Grades","Attendance","Announcements"],Siswa:["Courses","Materials","Assignments","Submissions","Grades","Attendance","Announcements"]};
function setupDatabase(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);Object.entries(SHEETS).forEach(([n,h])=>{let s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()===0)s.appendRow(h);s.setFrozenRows(1)});const u=ss.getSheetByName("Users");if(u.getLastRow()<2)u.getRange(2,1,3,8).setValues([["U001","admin","admin123","Administrator","Admin","","Aktif",new Date()],["U002","guru","guru123","Guru Demo","Guru","","Aktif",new Date()],["U003","siswa","siswa123","Siswa Demo","Siswa","","Aktif",new Date()]]);return{success:true,message:"Database siap"}}
function doGet(){return out({success:true,message:"SIAKAD & LMS API aktif",version:"2.0"})}
function doPost(e){try{const b=JSON.parse((e&&e.postData&&e.postData.contents)||"{}"),p=b.payload||{},a=b.action;if(a==="login")return out(login(p));if(a==="dashboard")return out(dashboard(p));if(a==="list")return out(list(p));if(a==="create")return out(mutate("create",p));if(a==="update")return out(mutate("update",p));if(a==="delete")return out(mutate("delete",p));if(a==="setup")return out(setupDatabase());return out({success:false,message:"Action tidak dikenal: "+a})}catch(err){return out({success:false,message:err.message})}}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function sheet(n){if(!SHEETS[n])throw Error("Entity tidak valid: "+n);const s=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(n);if(!s)throw Error("Sheet belum ada: "+n);return s}
function rows(n){const s=sheet(n);if(s.getLastRow()<2)return[];const v=s.getDataRange().getValues(),h=v.shift();return v.map((r,i)=>({__row:i+2,...Object.fromEntries(h.map((k,j)=>[k,r[j] instanceof Date?r[j].toISOString():r[j]]))})).filter(o=>Object.keys(o).some(k=>k!=="__row"&&o[k]!==""))}
function login(p){if(!p.username||!p.password)return{success:false,message:"Username dan password wajib diisi"};const u=rows("Users").find(x=>String(x.Username).toLowerCase()===String(p.username).toLowerCase()&&String(x.Password)===String(p.password)&&String(x.Status)==="Aktif");if(!u)return{success:false,message:"Username/password salah atau akun tidak aktif"};return{success:true,user:{username:u.Username,nama:u.Nama,role:u.Role,email:u.Email||""},permissions:ROLES[u.Role]||[]}}
function allowed(role,entity,action){if(role==="Admin")return true;if(["read","create","update"].includes(action))return(ROLES[role]||[]).includes(entity);return false}
function dashboard(p){return{success:true,stats:{students:rows("Students").length,teachers:rows("Teachers").length,classes:rows("Classes").length,subjects:rows("Subjects").length,courses:rows("Courses").length,materials:rows("Materials").length,assignments:rows("Assignments").length,submissions:rows("Submissions").length},announcements:rows("Announcements").slice(-5).reverse()}}
function list(p){const entity=p.entity,role=p.role||"Admin";if(!allowed(role,entity,"read"))throw Error("Akses ditolak");let data=rows(entity);if(p.search){const q=String(p.search).toLowerCase();data=data.filter(x=>Object.keys(x).some(k=>k!=="__row"&&String(x[k]).toLowerCase().includes(q)))}return{success:true,data:data.map(({__row,...x})=>x)}}
function mutate(action,p){const entity=p.entity,role=p.role||"Admin";if(!allowed(role,entity,action))throw Error("Akses ditolak");const s=sheet(entity),h=SHEETS[entity],d=p.data||{},id=p.id||d.ID;if(action==="create"){const newId=id||entity.substring(0,3).toUpperCase()+Date.now().toString().slice(-8);s.appendRow(h.map(k=>k==="ID"?newId:(d[k]??"")));return{success:true,message:"Data berhasil ditambahkan",id:newId}}const found=rows(entity).find(x=>String(x.ID)===String(id));if(!found)throw Error("Data dengan ID tersebut tidak ditemukan");if(action==="update"){h.forEach((k,i)=>{if(k!=="ID"&&Object.prototype.hasOwnProperty.call(d,k))s.getRange(found.__row,i+1).setValue(d[k])});return{success:true,message:"Data berhasil diperbarui"}}if(action==="delete"){s.deleteRow(found.__row);return{success:true,message:"Data berhasil dihapus"}}throw Error("Operasi tidak valid")}
